const { StyleSheet } = require("react-native");
export const stylesInfo = StyleSheet.create({
  modal: {
    flex: 1,
    justifyContent: "center", 
    alignItems: "center", 
    backgroundColor: "rgba(0, 0, 0, 0.7)", 
  },
  modalContent: {
    backgroundColor: "#f9f9f9", 
    padding: 25,
    width: "100%", 
    alignSelf: "center", 
  },
  titulo: {
    fontSize: 30,
    textAlign: "center",
    fontWeight: "bold",
    color: "#007bff", 
    marginBottom: 15,
    
  },
  direction: {
    fontSize: 18,
    color: "#333", 
    backgroundColor: 'white', 
    padding: 15,
    borderRadius: 10, 
    marginTop: 10,
    marginBottom: 10,
    border: "1px solid black",
    
  },
  tipoProperty: {
    fontSize: 18,
    color: "#333",
    backgroundColor: 'white', 
    padding: 15,
    borderRadius: 10, 
    marginTop: 10,
    marginBottom: 10,
    border: "1px solid black",
  },
  servicio: {
    fontSize: 18,
    color: "#333",
    backgroundColor: 'white', 
    padding: 15,
    borderRadius: 10, 
    marginTop: 10,
    marginBottom: 10,
    border: "1px solid black",
  },
  descripcion: {
    fontSize: 18,
    color: "#333",
    backgroundColor: "white", 
    padding: 15,
    borderRadius: 10, 
    marginTop: 10,
    marginBottom: 10,
    border: "1px solid black",
  },
  estado: {
    fontSize: 18,
    color: "#333",
    backgroundColor: 'white', 
    padding: 15,
    borderRadius: 10, 
    marginTop: 10,
    marginBottom: 10,
    border: "1px solid black",
  },
  contenedorsito: {
    margin: '3%',
    position: 'relative', 
    padding: 15,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10, 
    backgroundColor: 'white',
  },
  cosa: {
    position: 'absolute',
    top: -10, 
    left: 5, 
    backgroundColor: '#007bff', 
    color: 'white', 
    padding: 5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'black',
    zIndex: 1, 
  },
  scroll: {
    width: "100%",
    height: "575px",
  },
});
