const { StyleSheet } = require("react-native");
export const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "justify",
  },
  containerHead: {
    backgroundColor: "white",
    width: "90%",
    padding: "auto",
    margin: "2%",
    flex: 1,
    padding: 24,
    borderRadius: "10px",
    boxShadow: "5px 5px 5px grey",
    fontFamily: "Arial",
    fontSize: "24px",
    color: "white",
    textAlign: "center",
  },
  containerProm: {
    padding: "auto",
    backgroundColor: "white",
    width: "90%",
    margin: "2%",
    padding: "10",
    display: "between",
    borderRadius: "5px",
    boxShadow: "3px 3px 3px grey",
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "center",
    border: "1px solid black",
  },
  calificaciones: {
    backgroundColor: "white",
    width: "90%",
    margin: "2%",
    padding: "10",
    display: "between",
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "justify",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopRightRadius: 20,
    boxShadow: "5px 5px 5px grey",
    
  },
  calificacionItem: {
    flex:2,
    border: "1px solid black",
    borderRadius: "5px",
    padding: "10px",
    margin: "10px",
    boxShadow: "3px 3px 3px grey",
    backgroundColor: "white",
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "justify",
    display: "inline-block",
  },
  nota: {
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "justify",
  },
  comentario: {
    fontFamily: "Arial",
    fontSize: "16px",
    lineHeight: "1.5",
    textAlign: "justify",
  },
  titulo: {
    fontFamily: "Arial",
    fontSize: "30px",
    lineHeight: "1.5",
    textAlign: "center",
    color: "black",
    
  },
});
